### ISSUE TITLE
Document how to create a collection-specfic display

### ISSUE THREAD

**Issue by mjordan** [Islandora-Labs/islandora_solr_collection_view#13]
It is possible to create displays that apply to specific collections. Views FTW. Here are the steps:
1. Add a new block display to the view. You probably want to name it so it's clear which collection it applies to.
2. Add a filter to the new display, configuring it so that "RELS_EXT_isMemberOfCollection_uri_ms" is equal to your collection PID in the form "info:fedora/your:pid".
3. When you save the view, a new block is created with the name you gave the display.
   1. In Structure > Blocks, add the new block to the "Content" region.
   2. In the block's "Configure" settings, make the block only show up on the page for the specific collection. To do this, in the "Show block on specific pages" settings, select "Only the listed pages" and enter "islandora/object/your:pid".
4. Tell Views to not show the default block display for each collection that has its own block. Otherwise, both the default display and the collection-specific display will show up. To do this, for each collection that has its own block display, add a filter criteria to the default display so that "RELS_EXT_isMemberOfCollection_uri_ms" is _not_ equal to your collection PID in the form 'info:fedora/your:pid. 

If someone (maybe @librarychik ?) could test these instructions, I'd be happy to add them to the README.

**Comment by librarychik** [comment]
I tested and the instructions work as described.  
**Note**:
Re: step 4.  You have to add a new filter  _"RELS_EXT_isMemberOfCollection_uri_ms" is not equal to your collection PID in the form 'info:fedora/your:pid."_ for each block you add.  

Also, I had a space in front of the "info:fedora/your:pid" in the filter for step 2 and it didn't work (of course), something to watch for if you're copying/pasting.

**Comment by mjordan** [comment]
@librarychik thanks for the feedback. I've added some new text to step 4 as per your suggestion. Please let me know if that is clear enough.

About the leading space issue, that would apply to filters from any view, not just this one, so I'd rather not document it in this module's README.

If this documentation is ready to add to the README I can open a pull request. If not, let me know!

Revised version starts here:

It is possible to create displays that apply to specific collections. Views FTW. Here are the steps:
1. Add a new block display to the view. You probably want to name it so it's clear which collection it applies to.
2. Add a filter to the new display, configuring it so that "RELS_EXT_isMemberOfCollection_uri_ms" is equal to your collection PID in the form "info:fedora/your:pid".
3. When you save the view, a new block is created with the name you gave the display.
   1. In Structure > Blocks, add the new block to the "Content" region.
   2. In the block's "Configure" settings, make the block only show up on the page for the specific collection. To do this, in the "Show block on specific pages" settings, select "Only the listed pages" and enter "islandora/object/your:pid".
4. Tell Views to not show the default block display for each collection that has its own block. Otherwise, both the default display and the collection-specific display will show up. To do this, for each collection that has its own block display (in other words, for each collection-specific block display you create), add a filter criteria to the default display so that "RELS_EXT_isMemberOfCollection_uri_ms" is _not_ equal to your collection PID in the form 'info:fedora/your:pid.

**Comment by librarychik** [comment]
Looks good!  :+1:

**Comment by mjordan** [comment]
Thanks! @rosiel to save a PR mind if I also add a "Maintainer" section to the README with my name in it? Want to be co-maintainer (just say no if not).

**Comment by rosiel** [comment]
Done! Thanks for your patience. 

And sorry that I accidentally pushed! I thought I was pushing to rosiel but it redirected to Islandora Labs. Please allow it, since it's adding your name to the readme.

**Comment by mjordan** [comment]
Thanks - I have no problem with your push. I'll open a PR to update the README as above later today. Maybe @librarychik can merge it since she did the review....

**Comment by librarychik** [comment]
Sure thing.

**Comment by librarychik** [comment]
As it turns out, I don't have write access.  @rosiel  can you merge?  thx

**Comment by manez** [comment]
I'll grab it 😄

**Comment by rosiel** [comment]
Thanks @manez . Is this issue good to close?

**Comment by mjordan** [comment]
Yup.
