### ISSUE TITLE
Needs CONTRIBUTING.md

### ISSUE THREAD

**Issue by rosiel** [Islandora-Labs/islandora_solr_collection_view#15]
I propose something like:
---

# How To Contribute To islandora_solr_collection_view

Islandora welcomes community input! You're welcome to contribute by:
* making a pull request against this repo
* using the Github Issues in this repo

By participating in this project, you agree to abide by the Islandora [code of conduct].

[code of conduct]: http://islandora.ca/codeofconduct

## Workflow and merging 

The maintainers of islandora_solr_collection_view may:
* merge anyone's pull requests (except their own, and see note below)
* merge without review
* merge without waiting a courtesy period

As this repository belongs to the Islandora Foundation, anyone contributing code (pull requests) must have a [CLA] on file.

[CLA]: https://github.com/Islandora/islandora/blob/7.x/CONTRIBUTING.md#contribute-code

**Comment by mjordan** [comment]
@rosiel Great suggestion. I'm in favor of this workflow. One question however: in the "merge anyone's pull requests (except their own, and see note below)" bullet point, what note below are you referring to?

We also need a pull request template - can you add one to this PR?

**Comment by rosiel** [comment]
It referred to the fact that only PRs from folks with CLA's can be merged (maybe I should prefix it with "Note:"?)

**Comment by mjordan** [comment]
~~Or an asterisk?~~ "Note:" sounds great.
