### ISSUE TITLE
Who may merge sole maintainer's PRs?

### ISSUE THREAD

**Issue by mjordan** [Islandora-Labs/islandora_solr_collection_view#17]
@rosiel sorry I didn't catch this earlier, but the CONTRIBUTING.md says:

* Only maintainers of this module may merge pull requests.
* A maintainer may merge anyone's pull requests (except their own)

But if there is only one maintainer as is the case now (Hi! 😄), who is able to merge PRs that the maintainer opens?

**Comment by rosiel** [comment]
Hi! Um. Well yes that is a problem!

Is "(including their own)" ok?

Also, I can co-maintain if you like.

**Comment by mjordan** [comment]
I'd say including their own is OK, and sure, it'd be great to have a co-maintainer! I can take care of this change over the weekend if you want.

**Comment by manez** [comment]
It's like a GitHub [Barber Paradox](https://en.wikipedia.org/wiki/Barber_paradox) 😄 

What about "The maintainer(s) of this module and any Islandora Committer may merge pull requests," so you have at least as many potential mergers as the old way, plus maintainers?

**Comment by mjordan** [comment]
Thanks @rosiel!

**Comment by mjordan** [comment]
@manez I don't have permission to change settings on this repo. Can you set it so that people can merge approve/merge their own PRs?

**Comment by manez** [comment]
@mjordan I _think_ I have it turned off now, for administrators only (which would be maintainers and Committers)
