### ISSUE TITLE
Flesh out README

### ISSUE THREAD

**Issue by mjordan** [Islandora-Labs/islandora_solr_collection_view#2]
I'm happy to start fleshing out the README for this module.

**Comment by mjordan** [comment]
Code in https://github.com/mjordan/islandora_solr_collection_view/tree/issue-2 ready for PR.

**Comment by mjordan** [comment]
These changes are also included in the PR for #5 (making a PR for this issue redundant).

**Comment by rosiel** [comment]
Fixed with 99732c37ceb4a81575b5e358e096dcee1c0a3907
