### ISSUE TITLE
OK to add to Islandora Awesome?

### ISSUE THREAD

**Issue by mjordan** [Islandora-Labs/islandora_solr_collection_view#8]
As "under development", of course.

**Comment by manez** [comment]
I would say so - that's more or less the purpose of having the "In Development" tag as one of the bits of information we require.

**Comment by mjordan** [comment]
OK, PR is at https://github.com/manez/islandora_awesome/pull/16.

**Comment by mjordan** [comment]
I'll close this since the PR has been merged.
